/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import DAO.CandidatDAO;
import DAO.EmployeDAO;
import DAO.HistoriqueDAO;
import DAO.UserDAO;
import beans.Candidat;
import beans.Employe;
import beans.Historique;
import beans.User;
import classe_special.Confirm;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fofana
 */
public class PanelHistorique extends javax.swing.JPanel {
 
    boolean modifier;
    /**
     * Creates new form PanelUtilisateur
     */
    public PanelHistorique() {
        initComponents();
        liste();
        combo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameAjouter = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        btnEnregistrer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCandidat = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPoste = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDebut = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Historique = new classe_special.Tableaux();
        btnAjouter1 = new javax.swing.JLabel();
        btnModifier1 = new javax.swing.JLabel();
        btnSupprimer1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        frameAjouter.getContentPane().setBackground(Color.WHITE);
        frameAjouter.setAlwaysOnTop(true);
        frameAjouter.setMinimumSize(new java.awt.Dimension(407, 431));
        frameAjouter.setResizable(false);
        frameAjouter.setSize(new java.awt.Dimension(407, 431));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnEnregistrer.setBackground(new java.awt.Color(0, 102, 255));
        btnEnregistrer.setForeground(new java.awt.Color(255, 255, 255));
        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        jLabel2.setText("Date Debut");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ajouter User");

        jLabel1.setText("Poste");

        jLabel4.setText("Candidat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPoste)
                            .addComponent(txtCandidat, 0, 196, Short.MAX_VALUE)
                            .addComponent(txtDebut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPoste, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCandidat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        frameAjouter.pack();
        frameAjouter.setLocationRelativeTo(null);

        javax.swing.GroupLayout frameAjouterLayout = new javax.swing.GroupLayout(frameAjouter.getContentPane());
        frameAjouter.getContentPane().setLayout(frameAjouterLayout);
        frameAjouterLayout.setHorizontalGroup(
            frameAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameAjouterLayout.setVerticalGroup(
            frameAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        tb_Historique.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Poste", "Debut le", "Candidat"
            }
        ));
        tb_Historique.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_HistoriqueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Historique);

        btnAjouter1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAjouter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ajouter.png"))); // NOI18N
        btnAjouter1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjouter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjouter1MouseClicked(evt);
            }
        });

        btnModifier1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnModifier1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/modifier.png"))); // NOI18N
        btnModifier1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModifier1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifier1MouseClicked(evt);
            }
        });

        btnSupprimer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSupprimer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/supprimer.png"))); // NOI18N
        btnSupprimer1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSupprimer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimer1MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Candidat Retenus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnAjouter1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModifier1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSupprimer1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSupprimer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAjouter1)
                            .addComponent(btnModifier1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 395, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouter1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjouter1MouseClicked
        jLabel5.setText("Ajouter Historique");
        frameAjouter.setVisible(true);
        modifier=false;
        txtPoste.setText("");
        txtCandidat.setEnabled(true);
    }//GEN-LAST:event_btnAjouter1MouseClicked

    private void btnModifier1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifier1MouseClicked
        int index = tb_Historique.getSelectedRow();
        if (index==-1){
            JOptionPane.showMessageDialog(this,"Veuillez selectionnez une ligne");
        }
        else {
            jLabel5.setText("Modifier Historique");
            txtCandidat.setEnabled(false);
            frameAjouter.setVisible(true);
            modifier=true;
        }
    }//GEN-LAST:event_btnModifier1MouseClicked

    private void btnSupprimer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimer1MouseClicked
        int index = tb_Historique.getSelectedRow();
        if (index==-1){
            JOptionPane.showMessageDialog(this,"Veuillez selectionnez une ligne");
        }
        else {
            new Confirm().affiche("Supprimer","Etes vous sur de vouloir Supprimer!!!", new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    int index = tb_Historique.getSelectedRow();
                    int id = (int)tb_Historique.getValueAt(index,0);
                    HistoriqueDAO udao = new HistoriqueDAO();
                    udao.supprimer(id);
                    vider();
                    liste();
                }
            });
        }
    }//GEN-LAST:event_btnSupprimer1MouseClicked

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        String poste=txtPoste.getText();
        Date debut=txtDebut.getDate();
        
        String emp=txtCandidat.getSelectedItem().toString();
        int index=emp.indexOf(" ");
        String id=emp.substring(0, index);
        int idCandidat=Integer.parseInt(id);
        
        HistoriqueDAO udao=new HistoriqueDAO();
        
        if(poste.equals("")){
            JOptionPane.showMessageDialog(this,"Veuillez Remplir tous les champs");
        }
        else if(modifier==false){
            Historique u=new Historique(idCandidat, poste, debut);
            udao.inserer(u);
            vider();liste();
            frameAjouter.setVisible(false);
        }
        else if(modifier==true){
            int ligne=tb_Historique.getSelectedRow();
            int idUser =(int)tb_Historique.getValueAt(ligne, 0);
            Historique u=new Historique(idCandidat, poste, debut);
            udao.modifier(u, idUser);
            vider();liste();
            frameAjouter.setVisible(false);
        }
        
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void tb_HistoriqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_HistoriqueMouseClicked
        int index = tb_Historique.getSelectedRow();
        if(index!=-1){
            int id = (int)tb_Historique.getValueAt(index,0);
            HistoriqueDAO udao=new HistoriqueDAO();
            Historique u=udao.rechercher(id);
            txtPoste.setText(u.getPoste());
            txtDebut.setDate(u.getDateDebut());
            
            CandidatDAO edao = new CandidatDAO();
            Candidat employe = edao.rechercher(u.getCandidat());
            String emp=employe.getIdCandidat()+" "+employe.getNom()+" "+employe.getPrenom();
            txtCandidat.setSelectedItem(emp);
        }
    }//GEN-LAST:event_tb_HistoriqueMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAjouter1;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JLabel btnModifier1;
    private javax.swing.JLabel btnSupprimer1;
    private javax.swing.JFrame frameAjouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private classe_special.Tableaux tb_Historique;
    private javax.swing.JComboBox<String> txtCandidat;
    private com.toedter.calendar.JDateChooser txtDebut;
    private javax.swing.JTextField txtPoste;
    // End of variables declaration//GEN-END:variables

public void liste(){
    HistoriqueDAO udao = new HistoriqueDAO();
    CandidatDAO edao=new CandidatDAO();
        List<Historique> user = udao.liste();
        
        for (int i = 0; i < user.size(); i++) {
            Candidat em=edao.rechercher(user.get(i).getCandidat());
            String nom=em.getNom()+" "+em.getPrenom();
            ((DefaultTableModel) tb_Historique.getModel()).addRow(new Object[]{
                  user.get(i).getIdHistorique(),
                  user.get(i).getPoste(),
                  user.get(i).getDateDebut(),
                  nom
            });

    }
}
public void vider(){
        txtPoste.setText("");
        txtDebut.setDate(null);
        DefaultTableModel model = (DefaultTableModel) tb_Historique.getModel();
        int n = model.getRowCount();
        for (int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
    }
public void combo(){
    CandidatDAO edao=new CandidatDAO();
    List<Candidat> employe=edao.liste();
    for (int i = 0; i < employe.size(); i++){
        String emp=employe.get(i).getIdCandidat()+" "+employe.get(i).getNom()+" "+employe.get(i).getPrenom();
        txtCandidat.addItem(emp);
    }
}

}
