/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import DAO.DepartementDAO;
import DAO.EmployeDAO;
import DAO.EquipeDAO;
import DAO.PrimeDAO;
import beans.Departement;
import beans.Employe;
import beans.Equipe;
import beans.Prime;
import classe_special.Confirm;
import classe_special.EventCallBack;
import classe_special.EventTextField;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fofana
 */
public class PanelEmploye extends javax.swing.JPanel {
 
    boolean modifier;
    /**
     * Creates new form PanelUtilisateur
     */
    public PanelEmploye() {
        initComponents();
        liste();
        combo();
        textSearch1.addEvent(new EventTextField() {
        @Override
        public void onPressed(EventCallBack call) {
        vider();
        EmployeDAO pdao = new EmployeDAO();
        List<Employe> eq = pdao.recherche(textSearch1.getText());
        
        for (int i = 0; i < eq.size(); i++) {
            ((DefaultTableModel) tb_Employe.getModel()).addRow(new Object[]{
                  eq.get(i).getIdEmploye(),
                  eq.get(i).getNom(),
                  eq.get(i).getPrenom(),
                  eq.get(i).getDateNaissance(),
                  eq.get(i).getDateEmbauche(),
                  eq.get(i).isGenre(),
                  eq.get(i).getPoste(),
                  eq.get(i).getSalaireDeBase(),
                  eq.get(i).geteMail(),
                  eq.get(i).getIdDepartement(),
                  eq.get(i).getIdEquipe() 
            });

        }           
          }

            @Override
            public void onCancel() {
            }

        
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameAjouter = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnEnregistrer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtGenre = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPoste = new javax.swing.JTextField();
        txtDepartement = new javax.swing.JComboBox<>();
        txtEquipe = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtDateNaissance = new com.toedter.calendar.JDateChooser();
        txtSalaire = new javax.swing.JTextField();
        frameAddPrime = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMontant = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtMotif = new javax.swing.JTextField();
        employeText = new javax.swing.JToggleButton();
        btnAddPrime = new javax.swing.JButton();
        framePrimeListe = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPrime = new classe_special.Tableaux();
        jLabel16 = new javax.swing.JLabel();
        btnPayé = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Employe = new classe_special.Tableaux();
        btnAjouter1 = new javax.swing.JLabel();
        btnModifier1 = new javax.swing.JLabel();
        btnSupprimer1 = new javax.swing.JLabel();
        textSearch1 = new classe_special.TextSearch();
        jLabel3 = new javax.swing.JLabel();
        btnPrime = new javax.swing.JLabel();
        btnPrimeListe = new javax.swing.JLabel();

        frameAjouter.getContentPane().setBackground(Color.WHITE);
        frameAjouter.setAlwaysOnTop(true);
        frameAjouter.setMinimumSize(new java.awt.Dimension(407, 529));
        frameAjouter.setResizable(false);
        frameAjouter.setSize(new java.awt.Dimension(407, 529));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ajouter Equipe");

        btnEnregistrer.setBackground(new java.awt.Color(0, 102, 255));
        btnEnregistrer.setForeground(new java.awt.Color(255, 255, 255));
        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        jLabel2.setText("Prenom");

        jLabel1.setText("Nom");

        jLabel4.setText("Genre");

        jLabel6.setText("DateNaissance");

        txtGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme" }));

        jLabel7.setText("Email");

        jLabel8.setText("Salaire");

        jLabel9.setText("Departement");

        jLabel10.setText("Poste");

        jLabel11.setText("Equipe");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 154, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrenom)
                    .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(txtGenre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail)
                    .addComponent(txtPoste, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(txtDepartement, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEquipe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDateNaissance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSalaire))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDepartement)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        frameAjouter.pack();
        frameAjouter.setLocationRelativeTo(null);

        javax.swing.GroupLayout frameAjouterLayout = new javax.swing.GroupLayout(frameAjouter.getContentPane());
        frameAjouter.getContentPane().setLayout(frameAjouterLayout);
        frameAjouterLayout.setHorizontalGroup(
            frameAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameAjouterLayout.setVerticalGroup(
            frameAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        frameAddPrime.setAlwaysOnTop(true);
        frameAddPrime.setMinimumSize(new java.awt.Dimension(365, 364));
        frameAddPrime.setSize(new java.awt.Dimension(365, 364));
        frameAddPrime.setLocationRelativeTo(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Ajouter une Prime");

        jLabel13.setText("Montant");

        jLabel14.setText("Motif");

        employeText.setText("Employe");
        employeText.setEnabled(false);

        btnAddPrime.setBackground(new java.awt.Color(51, 153, 255));
        btnAddPrime.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPrime.setText("Ajouter");
        btnAddPrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPrimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(employeText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMontant))
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMotif)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(btnAddPrime, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtMotif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(employeText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddPrime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameAddPrimeLayout = new javax.swing.GroupLayout(frameAddPrime.getContentPane());
        frameAddPrime.getContentPane().setLayout(frameAddPrimeLayout);
        frameAddPrimeLayout.setHorizontalGroup(
            frameAddPrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameAddPrimeLayout.setVerticalGroup(
            frameAddPrimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        framePrimeListe.setAlwaysOnTop(true);
        framePrimeListe.setMinimumSize(new java.awt.Dimension(656, 450));
        framePrimeListe.setResizable(false);
        framePrimeListe.setSize(new java.awt.Dimension(656, 450));
        framePrimeListe.setLocationRelativeTo(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Liste Prime");

        tbPrime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idPrime", "Montant", "Motif", "Status"
            }
        ));
        jScrollPane2.setViewportView(tbPrime);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("jLabel16");

        btnPayé.setBackground(new java.awt.Color(0, 102, 255));
        btnPayé.setForeground(new java.awt.Color(255, 255, 255));
        btnPayé.setText("Payé");
        btnPayé.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayéActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(btnPayé)))
                        .addGap(0, 119, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPayé)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout framePrimeListeLayout = new javax.swing.GroupLayout(framePrimeListe.getContentPane());
        framePrimeListe.getContentPane().setLayout(framePrimeListeLayout);
        framePrimeListeLayout.setHorizontalGroup(
            framePrimeListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        framePrimeListeLayout.setVerticalGroup(
            framePrimeListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        tb_Employe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idEmploye", "Nom", "Prenom", "date Naissance", "Embauche", "Genre", "Poste", "Salaire", "eMail", "Departement", "Equipe"
            }
        ));
        tb_Employe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_EmployeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Employe);

        btnAjouter1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAjouter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ajouter.png"))); // NOI18N
        btnAjouter1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjouter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjouter1MouseClicked(evt);
            }
        });

        btnModifier1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnModifier1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/modifier.png"))); // NOI18N
        btnModifier1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModifier1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifier1MouseClicked(evt);
            }
        });

        btnSupprimer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSupprimer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/supprimer.png"))); // NOI18N
        btnSupprimer1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSupprimer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupprimer1MouseClicked(evt);
            }
        });

        textSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSearch1ActionPerformed(evt);
            }
        });
        textSearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textSearch1KeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gestion du Personnel");

        btnPrime.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnPrime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPrime.setText("Add Prime");
        btnPrime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrimeMouseClicked(evt);
            }
        });

        btnPrimeListe.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnPrimeListe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPrimeListe.setText("Prime Liste");
        btnPrimeListe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrimeListe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrimeListeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnAjouter1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModifier1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSupprimer1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(btnPrime, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrimeListe, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSupprimer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAjouter1)
                                .addComponent(btnModifier1)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrime)
                    .addComponent(btnPrimeListe))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouter1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjouter1MouseClicked
        jLabel5.setText("Ajouter Employe");
        frameAjouter.setVisible(true);
        modifier=false;
        txtNom.setText("");
        txtPrenom.setText("");
        txtDateNaissance.setDate(null);
        txtEmail.setText("");
        txtPoste.setText("");
        txtSalaire.setText("");
    }//GEN-LAST:event_btnAjouter1MouseClicked

    private void btnModifier1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifier1MouseClicked
        int index = tb_Employe.getSelectedRow();
        if (index==-1){
            JOptionPane.showMessageDialog(this,"Veuillez selectionnez une ligne");
        }
        else {
            jLabel5.setText("Modifier Employe");
            frameAjouter.setVisible(true);
            modifier=true;
        }
    }//GEN-LAST:event_btnModifier1MouseClicked

    private void btnSupprimer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupprimer1MouseClicked
        int index = tb_Employe.getSelectedRow();
        EquipeDAO edao=new EquipeDAO();
        if (index==-1){
            JOptionPane.showMessageDialog(this,"Veuillez selectionnez une ligne");
        }
        else {
            new Confirm().affiche("Supprimer","Etes vous sur de vouloir Supprimer!!!", new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    int index = tb_Employe.getSelectedRow();
                    int id = (int)tb_Employe.getValueAt(index,0);
                    EmployeDAO cdao = new EmployeDAO();
                    cdao.supprimer(id);
                    vider();
                    edao.updateMembre();
                    liste();
                    
                }
            });
        }
    }//GEN-LAST:event_btnSupprimer1MouseClicked

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        String chef=txtPrenom.getText();
        String nom=txtNom.getText();
        String prenom=txtPrenom.getText();
        Date dateNaiss=txtDateNaissance.getDate();
        String sexe=txtGenre.getSelectedItem().toString();
        boolean genre=false;
        if(sexe.equals("Homme")){
            genre=true;
        }
        double salaire=Double.parseDouble(txtSalaire.getText());
        String eMail=txtEmail.getText();
        String poste=txtPoste.getText();
        
        String dpt=txtDepartement.getSelectedItem().toString();
        int indexFind=dpt.indexOf(" ");
        String indexDpt=dpt.substring(0, indexFind);
        int idDepartement=Integer.parseInt(indexDpt);
        
        String eq=txtEquipe.getSelectedItem().toString();
        int indexFine=eq.indexOf(" ");
        String indexEq=eq.substring(0, indexFine);
        int idEquipe=Integer.parseInt(indexEq);
        
        
        EmployeDAO edao=new EmployeDAO();
        EquipeDAO eqdao=new EquipeDAO();
        
        if(nom.equals("")||chef.equals("")){
            JOptionPane.showMessageDialog(this,"Veuillez Remplir tous les champs");
        }
        else if(modifier==false){
            Employe e=new Employe(nom, prenom, dateNaiss, genre, poste, salaire, eMail, idDepartement, idEquipe);
            edao.inserer(e);
            vider();liste();
            frameAjouter.setVisible(false);
        }
        else if(modifier==true){
            int index = tb_Employe.getSelectedRow();
             int id = (int)tb_Employe.getValueAt(index,0);
             Employe e=new Employe(nom, prenom, dateNaiss, genre, poste, salaire, eMail, idDepartement, idEquipe);
            edao.modifier(e, id);
            vider();
            liste();
            frameAjouter.setVisible(false);
        }
        eqdao.updateMembre();
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void tb_EmployeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_EmployeMouseClicked
        int index = tb_Employe.getSelectedRow();
        if (index!=-1){
          int id = (int)tb_Employe.getValueAt(index,0);
            EmployeDAO edao = new EmployeDAO();
            Employe eq = edao.rechercher(id);
            txtPrenom.setText(eq.getPrenom());
            txtNom.setText(eq.getNom());
            txtDateNaissance.setDate(eq.getDateNaissance());
            DepartementDAO ddao=new DepartementDAO();
            Departement dpt=ddao.rechercher(eq.getIdDepartement());
            EquipeDAO eqdao=new EquipeDAO();
            Equipe equipe=eqdao.rechercher(eq.getIdEquipe());
            
            txtDepartement.setSelectedItem(dpt.getIdDepartement()+" "+dpt.getNomDepartement());
            txtEmail.setText(eq.geteMail());
            txtEquipe.setSelectedItem(equipe.getIdEquipe()+" "+equipe.getNomEquipe());
            txtGenre.setSelectedItem("Homme");
            if(eq.isGenre()==false) txtGenre.setSelectedItem("Femme");
            txtPoste.setText(eq.getPoste());
            txtSalaire.setText(eq.getSalaireDeBase()+"");
        }
    }//GEN-LAST:event_tb_EmployeMouseClicked

    private void textSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSearch1ActionPerformed
     
    }//GEN-LAST:event_textSearch1ActionPerformed

    private void btnPrimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrimeMouseClicked
        int index = tb_Employe.getSelectedRow();
        if (index==-1){
            JOptionPane.showMessageDialog(this,"Veuillez selectionnez un employe");
        }
        else{
            EmployeDAO edao=new EmployeDAO();
            int id=(int) tb_Employe.getValueAt(index, 0);
            Employe emp=edao.rechercher(id);
            employeText.setText("Employé:"+emp.getNom()+" "+emp.getPrenom());
            frameAddPrime.setVisible(true);
        }
    }//GEN-LAST:event_btnPrimeMouseClicked

    private void btnPrimeListeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrimeListeMouseClicked
        int index = tb_Employe.getSelectedRow();
        if (index==-1){
            JOptionPane.showMessageDialog(this,"Veuillez selectionnez un employe");
        }
        else{
            PrimeDAO pdao=new PrimeDAO();
            int id=(int) tb_Employe.getValueAt(index, 0);
            List<Prime> lst=pdao.listePrime(id);
            
            DefaultTableModel model = (DefaultTableModel) tbPrime.getModel();
            int n = model.getRowCount();
            for (int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
            }
            
            if(lst.size()==0){
                JOptionPane.showMessageDialog(this,"Cet Employé n a jamais eu de prime");
            }
            else{
                EmployeDAO edao=new EmployeDAO();
                Employe emp=edao.rechercher(id);
                jLabel16.setText("Employé: "+emp.getNom()+" "+emp.getPrenom());
                for (int i = 0; i < lst.size(); i++) {
                  ((DefaultTableModel) tbPrime.getModel()).addRow(new Object[]{
                  lst.get(i).getIdPrime(),
                  lst.get(i).getMontant(),
                  lst.get(i).getMotif(),
                  lst.get(i).getStatut()
                });
                }
                framePrimeListe.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnPrimeListeMouseClicked

    private void btnAddPrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPrimeActionPerformed
        int index = tb_Employe.getSelectedRow();
        String motif=txtMotif.getText();
        String mo=txtMontant.getText();
                if (motif.equals("")||mo.equals("")){
            JOptionPane.showMessageDialog(this,"Veuillez Renseignez tous les champs");
        }
        else{
            double montant=Double.parseDouble(mo);
            String status="Non payer";
            int id = (int)tb_Employe.getValueAt(index,0);
            PrimeDAO pdao=new PrimeDAO();
            Prime p=new Prime(montant, status, motif, id);
            pdao.inserer(p);
            frameAddPrime.setVisible(false);
            JOptionPane.showMessageDialog(this,"Prime Ajouter avec Succes");
            
        }
        
    }//GEN-LAST:event_btnAddPrimeActionPerformed

    private void textSearch1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSearch1KeyPressed
       vider();
        EmployeDAO pdao = new EmployeDAO();
        List<Employe> eq = pdao.recherche(textSearch1.getText());
        
        for (int i = 0; i < eq.size(); i++) {
            ((DefaultTableModel) tb_Employe.getModel()).addRow(new Object[]{
                  eq.get(i).getIdEmploye(),
                  eq.get(i).getNom(),
                  eq.get(i).getPrenom(),
                  eq.get(i).getDateNaissance(),
                  eq.get(i).getDateEmbauche(),
                  eq.get(i).isGenre(),
                  eq.get(i).getPoste(),
                  eq.get(i).getSalaireDeBase(),
                  eq.get(i).geteMail(),
                  eq.get(i).getIdDepartement(),
                  eq.get(i).getIdEquipe() 
            });

        }
    }//GEN-LAST:event_textSearch1KeyPressed

    private void btnPayéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayéActionPerformed
        int index = tbPrime.getSelectedRow();
        if (index==-1){
            JOptionPane.showMessageDialog(this,"Veuillez selectionnez une prime");
        }
        else{
            int id=(int) tbPrime.getValueAt(index,0);
            
            PrimeDAO pdao=new PrimeDAO();
            Prime p=pdao.rechercher(id);
            
            pdao.modifierStatut("Payé", id);
            
            List<Prime> lst=pdao.listePrime(p.getIdEmploye());
            
            DefaultTableModel model = (DefaultTableModel) tbPrime.getModel();
            int n = model.getRowCount();
            for (int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
            }
            
            for (int i = 0; i < lst.size(); i++) {
                  ((DefaultTableModel) tbPrime.getModel()).addRow(new Object[]{
                  lst.get(i).getIdPrime(),
                  lst.get(i).getMontant(),
                  lst.get(i).getMotif(),
                  lst.get(i).getStatut()
                });
                }
        }
    }//GEN-LAST:event_btnPayéActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPrime;
    private javax.swing.JLabel btnAjouter1;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JLabel btnModifier1;
    private javax.swing.JButton btnPayé;
    private javax.swing.JLabel btnPrime;
    private javax.swing.JLabel btnPrimeListe;
    private javax.swing.JLabel btnSupprimer1;
    private javax.swing.JToggleButton employeText;
    private javax.swing.JFrame frameAddPrime;
    private javax.swing.JFrame frameAjouter;
    private javax.swing.JFrame framePrimeListe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private classe_special.Tableaux tbPrime;
    private classe_special.Tableaux tb_Employe;
    private classe_special.TextSearch textSearch1;
    private com.toedter.calendar.JDateChooser txtDateNaissance;
    private javax.swing.JComboBox<String> txtDepartement;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JComboBox<String> txtEquipe;
    private javax.swing.JComboBox<String> txtGenre;
    private javax.swing.JTextField txtMontant;
    private javax.swing.JTextField txtMotif;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPoste;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtSalaire;
    // End of variables declaration//GEN-END:variables
public void liste(){
    EmployeDAO edao = new EmployeDAO();
    DepartementDAO ddao=new DepartementDAO();
        List<Employe> eq = edao.liste();
        
        for (int i = 0; i < eq.size(); i++) {
            String genre="Homme";
            if(eq.get(i).isGenre()==false) genre="Femme";
            Departement dpt=ddao.rechercher(eq.get(i).getIdDepartement());
            ((DefaultTableModel) tb_Employe.getModel()).addRow(new Object[]{
                  eq.get(i).getIdEmploye(),
                  eq.get(i).getNom(),
                  eq.get(i).getPrenom(),
                  eq.get(i).getDateNaissance(),
                  eq.get(i).getDateEmbauche(),
                  genre,
                  eq.get(i).getPoste(),
                  eq.get(i).getSalaireDeBase(),
                  eq.get(i).geteMail(),
                  dpt.getNomDepartement(),
                  eq.get(i).getIdEquipe()
            });

    }
}

public void vider(){
        txtPrenom.setText("");
        txtNom.setText("");
        DefaultTableModel model = (DefaultTableModel) tb_Employe.getModel();
        int n = model.getRowCount();
        for (int i = n - 1; i >= 0; --i) {
            model.removeRow(i);
        }
    }
public void combo(){
    DepartementDAO ddao=new DepartementDAO();
    EquipeDAO edao=new EquipeDAO();
    List<Departement> dpt=ddao.liste();
    List<Equipe> eq=edao.liste();
    
    for(int i=0;i<dpt.size();i++){
        String d=dpt.get(i).getIdDepartement()+" "+dpt.get(i).getNomDepartement();
        txtDepartement.addItem(d);
    }
    for(int i=0;i<eq.size();i++){
        String e=eq.get(i).getIdEquipe()+" "+eq.get(i).getNomEquipe();
        txtEquipe.addItem(e);
    }
}

}
